### ISSUE TITLE
[BUG]  Screen Sharing window is appearing out of bounds of the monitor screen

### ISSUE THREAD

**Issue by mediocretwo** [Milkshiift/GoofCord#21]
### Description
I am trying to use screen sharing and when I click on the screen share icon and select the application from the portal window, the screen sharing window which allows me to select resolution is appearing on the bottom right corner of the monitor and it is out of bounds of the monitor. I have to use my keyboard shortcuts to drag it into the main screen again.

### Steps to Reproduce
log into discord, join a server and start screen sharing. The screen sharing window is appearing on the bottom right corner and mostly out of the screen bounds.

### Expected Behavior
The window for screen sharing menu should appear fully within the monitor boundaries.

### Actual Behavior
The screen sharing window is appearing in the bottom right corner of the screen and is mostly out of bounds of the monitor.

### Screenshots
Attaching the screenshot. Please look at the bottom right corner of the screen and you will see what I am talking about.

![sc](https://github.com/Milkshiift/GoofCord/assets/43803024/f6f84cc6-5036-447a-ba1d-9ffbfda45a59)

### Environment
- Operating System: Fedora Workstation 40, gnome DE on Wayland.
- Version: 1.4.2 (flatpak)

**Comment by Milkshiift** [comment]
I can't replicate the issue, but this should be theoretically fixed in https://github.com/Milkshiift/GoofCord/commit/079dce5ec66ced52f14485b1ec5cf1cc46c4a1a3
I made an AppImage build with the possible fix included, can you test it?
https://dropmefiles.net/en/4SBvs

**Comment by mediocretwo** [comment]
Hi, thanks for the appimage build. The bug was not there in the appimage you provided, the screensharing window was properly centered on the screen. When will this fix be added to the flatpak? Thanks.

**Comment by Milkshiift** [comment]
Thank you for testing. Closing the issue.
The fix will be available in the next version release, which should be soon

**Comment by double-hash** [comment]
Hey, 
Sorry for re-opening this issue but I still have this bug on the latest flatpak release. 

Btw, I can manage to successfully launch the screensharing stream by pressing the Return/Enter key even if I can't see properly the window, but I can't manage to click on the "Activate Audio" checkbox....

Note that contrary to the intial post screenshot, here the screensharing setup screen has his upper left corner centered to screen : 

![Image](https://github.com/user-attachments/assets/a05d888c-8abe-4540-8a03-abdc1479489d)

I'm using the latest flatpak release.
Operating System : PostMarketOS v25.06, gnome DE on Wayland
